<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BrowserSelector.Library.Core\BrowserSelector.Library.Core.csproj" />
    <ProjectReference Include="..\BrowserSelector.Library.Infrastructure\BrowserSelector.Library.Infrastructure.csproj" />
    <ProjectReference Include="..\..\BrowserSelector.Presentation\BrowserSelector.Presentation.csproj" />
  </ItemGroup>

</Project>
